# Generated by Django 4.1.7 on 2023-03-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_pasue',
            new_name='guest_can_pause',
        ),
    ]
